server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/brawlingdb
    username: squirter
    password: squirt123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    # explicit dialect (optional once connectivity is ok)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
