server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://10.0.40.186:5173"
              - "http://10.0.40.186:5174"
              - "http://10.0.40.186:5175"
              - "http://10.0.40.186:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: auth
          uri: http://authentification:8081
          predicates:
            - Path=/auth/**

        - id: users
          uri: http://authentification:8081
          predicates:
            - Path=/users
           

        - id: users-subpath
          uri: http://authentification:8081
          predicates:
            - Path=/users/**

        - id: player
          uri: http://player-service:8080
          predicates:
            - Path=/players/**
