server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://10.0.40.186"
            allowCredentials: true
            allowedMethods: ["GET","POST","PUT","DELETE","OPTIONS"]
            allowedHeaders: ["*"]

      routes:
        - id: auth
          uri: http://authentification:8081
          # remove preserveHostHeader so cookies default to gateway host
          predicates:
            - Path=/auth/**
          # OR, if you really need preserveHostHeader, uncomment:
          # filters:
          #   - RewriteResponseHeader=Set-Cookie,Domain=authentification,Domain=10.0.40.186

        
        - id: users
          uri: http://authentification:8081
          predicates:
            - Path=/users,/users/**


        - id: player
          uri: http://player-service:8080
          predicates:
            - Path=/players/**
