version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: squirter
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: squirter
      POSTGRES_PASSWORD: squirt123
      POSTGRES_DB: brawlingdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
